<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CMLPT015" ignored="0" name="Test" tests="6" failures="1" timestamp="04 Jun 2019 06:57:22 GMT" time="58.876" errors="0">
  <testcase name="postSyStemProcessTest" time="5.59" classname="com.pkg.testcases.SetSystemStatus"/>
  <testcase name="postSyStemProcessTest" time="4.482" classname="com.pkg.testcases.SetSystemStatus"/>
  <testcase name="postSyStemProcessTest" time="4.334" classname="com.pkg.testcases.SetSystemStatus"/>
  <testcase name="dataBaseValidation" time="17.913" classname="com.pkg.testcases.SetSystemStatus"/>
  <testcase name="dataBaseValidation" time="6.298" classname="com.pkg.testcases.SetSystemStatus">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.pkg.testcases.SetSystemStatus.dataBaseValidation(SetSystemStatus.java:164)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- dataBaseValidation -->
  <testcase name="dataBaseValidation" time="7.155" classname="com.pkg.testcases.SetSystemStatus"/>
</testsuite> <!-- Test -->
